---
- name: "CreateUser"
  hosts: Win_Servers
  tasks:
    - name: Create User
      win_user:
       name: steven
       password: subst@NTI@l
       state: present
       groups:
        - Users
        - Administrators
