---
- name: "CreateFile"
  hosts: win_servers
  tasks:
    - name: Create User
      win_user:
       name: joe
       password: subst@NTI@l
       state: present
       groups:
        - Users
        - Administrators
