---
- name: "CreateFile"
  hosts: win
  tasks:
    - name: Create User
      win_user:
       name: steven
       password: subst@NTI@l
       state: present
       groups:
        - Users
        - Administrators
